### ISSUE TITLE
Improve SVG rendering size

### ISSUE THREAD

**Issue by morishin** [bdash-app/bdash-server#1]
🙄

<img width="1111" alt="スクリーンショット 2021-04-19 16 01 51" src="https://user-images.githubusercontent.com/1413408/115194655-b4dbce80-a128-11eb-9ab0-c0121959ea13.png">

**Comment by morishin** [comment]
https://css-tricks.com/scale-svg/

**Comment by hokaccha** [comment]
fixed by https://github.com/bdash-app/bdash-server/commit/2aba0698a4af2786801ed72ae125d78a09b8a03a
