### ISSUE TITLE
SQL文より結果を先に表示してほしい

### ISSUE THREAD

**Issue by hashcc** [bdash-app/bdash-server#15]
bdash servcerのページURLを開くときにユーザーが関心があるのは、SQL文ではなく、実行結果であることのほうが多いと思うので、実行結果→SQLの順に並び替えると良いと思ったのですがどうでしょうか？

**Comment by morishin** [comment]
実行結果は最大1000行まで表示するようにしていて、とても縦に長いHTML要素になることがあるので最下部に位置していました。
もっと見る的な機能(要素を fold/unfold する機能)とセットであれば実行結果を中段に位置させるのも良いかもしれませんが、今のまま上下を入れ替えるのは躊躇があります 🙇‍♂️  
あとはスクロールさせるのではなくてクリックで実行結果や SQL セクションへジャンプできる目次機能などの解もアリかも?

**Comment by hashcc** [comment]
> もっと見る的な機能(要素を fold/unfold する機能)とセットであれば実行結果を中段に位置させるのも良いかもしれませんが、今のまま上下を入れ替えるのは躊躇があります 🙇‍♂️

なるほど、僕も今のまま入れ替えるのは問題がありそうに思いました。
「もっと見る」良さそうですが、実行結果が常に多いような人にとっては毎回 unfold するってのも予想できて、痛し痒し感ありますね。

僕の対案としては↓こんな感じで、

<img src="https://user-images.githubusercontent.com/4290598/149881449-be8910b5-6010-4968-bc8d-bf6a457deffa.png" width="500">

- 実行結果を上に持ってくる
- 結果全体を600pxとか一定程度の高さにして、内部でスクロールするようにする
- (optional) ヘッダをスクロール時にくっつけておいて、スクロールした時でも表全体をわかりやすくする

とかはどうでしょうか？

> あとはスクロールさせるのではなくてクリックで実行結果や SQL セクションへジャンプできる目次機能などの解もアリかも?

これは上述のようなコンテンツの見せ方で解決出来そうにないねとなったら検討したほうがいいかもしれませんね（人はナビゲーションよりコンテンツにまず着目すると思うので）

**Comment by morishin** [comment]
その案良さそうです！

**Comment by hashcc** [comment]
PR出しました https://github.com/bdash-app/bdash-server/pull/23
