### ISSUE TITLE
faviconほしい

### ISSUE THREAD

**Issue by aamine** [bdash-app/bdash-server#2]
です。

**Comment by morishin** [comment]
Bdash の App アイコンと同じものを設定していますが、これではなく？

https://github.com/bdash-app/bdash-server/blob/main/public/favicon.ico

[![Image from Gyazo](https://i.gyazo.com/bbd92a020f3d93588f013db4f48307e5.png)](https://gyazo.com/bbd92a020f3d93588f013db4f48307e5)

**Comment by aamine** [comment]
あれーもう設定してるのか……。どれだけアクセスしてもChrome氏が表示してくれないの……

<img width="283" alt="スクリーンショット 2021-04-20 9 47 56" src="https://user-images.githubusercontent.com/1703556/115320824-8825c680-a1bd-11eb-9276-a190bb619733.png">

**Comment by aamine** [comment]
スーパーリロードで出ました！ 大変失礼いたしました！！
