### ISSUE TITLE
Suggestion: do not update description in shared updates

### ISSUE THREAD

**Issue by funwarioisii** [bdash-app/bdash-server#32]
Hi.
I am using bdash server and app to share queries and their execution results.
And I often write the query description in bdash server.
But when I update the query and the results from the app, the description is overwritten.

Wouldn't it be more convenient if the description is not updated?

Bdash app version: 1.15.2 (1.15.2)

**Comment by morishin** [comment]
This is unexpected behavior 😣 I'll fix it. Thank you
