### ISSUE TITLE
Long description text overflows

### ISSUE THREAD

**Issue by morishin** [bdash-app/bdash-server#4]
🙄 
![スクリーンショット 2021-04-19 23 00 58](https://user-images.githubusercontent.com/1413408/115249224-5da71f80-a163-11eb-9316-4ed6ff5ab7b8.png)

**Comment by hokaccha** [comment]
fixed by https://github.com/bdash-app/bdash-server/commit/5db8067e36c9330e37890e001143e9503f2b2a11
