### ISSUE TITLE
SQLを手元のBdashに落としたい

### ISSUE THREAD

**Issue by ragi256** [bdash-app/bdash-server#6]
実行とまでは言わないので「誰かが書いたクエリを手元に持ってきて自分でも書き換えて実行してみる」の流れをスムーズにしたい。
VSC拡張機能の InstallボタンのようにWebブラウザからBdashへ繋げるフローが作れればよさそう。

**Comment by hokaccha** [comment]
とりあえず SQL を Copy ボタンをつけてみた。理想ではないが多少マシになるかな。

![image](https://user-images.githubusercontent.com/39471/117992857-30bce580-b37a-11eb-9c1e-3a696b76b443.png)
